services:
  discord-bot:
    build: .
    container_name: discord-bot
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
